name: fluvvm
description: Fluvvm is a lightweight library that removes some boilerplate code from
  your Flutter apps that is using `provider` and the `MVVM` architecture.
# version is automatically bumped by the release script
version: 0.0.0
repository: https://github.com/Dennisaurus-Rex/fluvvm
issue_tracker: https://github.com/Dennisaurus-Rex/fluvvm/issues
environment:
  sdk: '^3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
