
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          environment: pub.dev
