
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pub.dev
    steps:
      - uses: actions/checkout@v3
      # - uses: dart-lang/setup-dart@v1
      # - uses: subosito/flutter-action@v2
        # with:
        #   channel: 'stable'
      - name: Update pubspec.yaml
        run: |
          pip3 install gitpython 
          pip3 install pyyaml
          python3 release.py
      # - name: Install dependencies
      #   run: flutter pub get
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      # - name: Analyze project source
      #   run: dart analyze --fatal-infos
      # - name: Dry run
      #   run: dart pub publish --dry-run
      # - name: Publish
      #   run: dart pub publish --force
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: release-${{ github.event.release.tag_name }}
          title: release-${{ github.event.release.tag_name }}
          body: Automatic PR for release-${{ github.event.release.tag_name }}
          branch: release-${{ github.event.release.tag_name }}
          base: master
      